// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPCbjIuf6y7XI2YjGLdVb0VTU80Nn13pA',
    appId: '1:638126716300:android:0550a6d824573534ab92a9',
    messagingSenderId: '638126716300',
    projectId: 'assignment5-c2281',
    storageBucket: 'assignment5-c2281.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh-lCnsOXH9czgTwvGAI1fY1B2uSmlKrg',
    appId: '1:638126716300:ios:f4d2c888072c89a7ab92a9',
    messagingSenderId: '638126716300',
    projectId: 'assignment5-c2281',
    storageBucket: 'assignment5-c2281.appspot.com',
    iosClientId: '638126716300-g5ddt2r3b4rpsm7ru9bhq16vs84oqpg2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication11',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYaIM3G8WuRTzQq3vBkvLfCExSqIcHz38',
    appId: '1:638126716300:web:15bbd8d438d78740ab92a9',
    messagingSenderId: '638126716300',
    projectId: 'assignment5-c2281',
    authDomain: 'assignment5-c2281.firebaseapp.com',
    storageBucket: 'assignment5-c2281.appspot.com',
    measurementId: 'G-2MZQCE2TZ2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBh-lCnsOXH9czgTwvGAI1fY1B2uSmlKrg',
    appId: '1:638126716300:ios:f4d2c888072c89a7ab92a9',
    messagingSenderId: '638126716300',
    projectId: 'assignment5-c2281',
    storageBucket: 'assignment5-c2281.appspot.com',
    iosClientId: '638126716300-g5ddt2r3b4rpsm7ru9bhq16vs84oqpg2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication11',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYaIM3G8WuRTzQq3vBkvLfCExSqIcHz38',
    appId: '1:638126716300:web:a25b92f075c8b6a0ab92a9',
    messagingSenderId: '638126716300',
    projectId: 'assignment5-c2281',
    authDomain: 'assignment5-c2281.firebaseapp.com',
    storageBucket: 'assignment5-c2281.appspot.com',
    measurementId: 'G-8RSG87M3P8',
  );

}